### ISSUE TITLE
POST to ADFS for JWT

### ISSUE THREAD

**Issue by SMUPonies** [chrisprice/adfs-example-integration#1]
Hi Chris,

Very interesting topic.  Thanks for the work on it.  I am trying to get it working and am having trouble with step D.  I am able to get an authorization code back from ADFS (step C), but when I am redirected to http://localhost:3000/getAToken, I get a 404 back.  Does the index.js you have posted have support for that method?

So, I tried just sending a post to ADFS (using REST Easy for Firefox) with the query string you have listed in step D.  But, unfortunately ADFS just comes back with a generic "contact your administrator" message.

Any ideas how I can use the authorization code to get the JWT from ADFS?  Thanks!

**Comment by chrisprice** [comment]
Sorry, it's a long time since I did this myself so I'm not sure of the specifics anymore. From a quick look at the node code it looks like the endpoint is actually [`/callback`](https://github.com/chrisprice/adfs-example-integration/blob/master/index.js#L66) which is configured [here](https://github.com/chrisprice/adfs-example-integration/blob/master/index.js#L35). The steps in the post don't reference the node code so should be considered independent.

As for ADFS returning errors, if it's not listed in the blog post I'm afraid you're on your own. I have a hard enough time remembering what I had for breakfast let alone a post from last year! :smile:
